add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;
add_header Cross-Origin-Embedder-Policy "require-corp" always;
add_header Origin-Agent-Cluster "?1" always;
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'sha256-+Tv63f3xuCaXeXR+K0LvQBWyngghUeiyoFKp/OcbmBU=' 'sha256-0/mN3GoQ4nqniMY/TpGOVSaYR6F5cbNSNg4Jv8Ek624=' 'sha256-2KmbYisVbi6BTQsI+ymdO8Dltf6/c+NF1m3mXdDzw2w=' 'sha256-YoljRz09DZKRZEnU2d0ApObIWSSQV+8tpZamihM+Cug=' 'sha256-Z5m+Z2AEGDOfufZMoMWJJgequxZRvhqg9WxI2Cm5NIM=' 'sha256-cJ79glkSLJUdsoa6A2RpLhJHvcj137Sx1FVMGPHrmjE=' 'sha256-mZUZgmR99bJQMKmoClIrgCkBjEBXH17EHe9DiVVy1FE=' 'sha256-uW1Dzy54hfMD7LwI2VMhzPLnE2/JyEIcA43xbR708Ls='; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests" always;
